Delete unused tasks and pipeline definitions and update README
opendatahub-io/ai-edge pull request #277
Opened 2024-07-24 16:33 UTC by MarianMacik

## Description

* Removed duplicates and fixed README.
* README will be polished further after the Git Fetch pipeline is merged.
* Unified structure of  directories in `pipelines/tekton`. Now there are `templates` directories for secret templates and `example-pipelineruns` for example pipeline runs.
* Refactored variable names in shell tests to better reflect reality.

## How Has This Been Tested?
PR check.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2024-07-24 18:49 UTC, MarianMacik commented
/retest

2024-07-25 11:58 UTC, MarianMacik commented on manifests/kustomization.yaml
> -- https://raw.githubusercontent.com/tektoncd/catalog/main/task/github-open-pr/0.2/github-open-pr.yaml
This was moved to `tasks/kustomization.yaml` so it is grouped with other tasks.

2024-07-25 13:22 UTC, jackdelahunt approved these changes

2024-07-25 13:24 UTC, biswassri requested changes
@MarianMacik Some thoughts: 

1.  I was thinking we could maybe also add some blurb about the RHOAI Operator deployment. Something like: This manifest package will be built and deployed with the RHOAI Operator bundle. (Adding links in the future)
2. The Readme should be moved up into the manifest package because going forward the pipeline definition files would be residing there. So, when one looks for the pipelines the readme should be in the same location. 
3. When/If we move up the Readme, we need to remove the same templates from the Readme. We can have a smaller readme in example-pipelines for user reference.

2024-07-25 13:54 UTC, jackdelahunt commented
/lgtm

2024-07-25 14:29 UTC, biswassri commented
(For the records) After an offline discussion with @MarianMacik, we will re-visit the Readme contents/location after `git-fetch-pipeline` is merged in.

2024-07-25 14:31 UTC, biswassri commented
/lgtm

2024-07-25 14:33 UTC, biswassri commented
/approve

2024-07-25 14:35 UTC, MarianMacik commented
/approver (just because because @biswassri is not)

2024-07-25 14:35 UTC, MarianMacik commented
/approve (just because because @biswassri is not)

2024-07-25 14:39 UTC, merged