Create CONTRIBUTING.md
opendatahub-io/ai-edge pull request #79
Opened 2023-09-15 20:36 UTC by piotrpdev

## Description

Adds a guide for contributing to the root of the repo. Port of section of the same name from the internal onboarding doc (will likely remove it once this is merged).

Resolves #77 

## How Has This Been Tested?

- **Visual Inspection**: Conducted a rigorous visual inspection using the latest in human optical technology to ensure the markdown file meets the highest standards of quality.

- **Scroll Test**: Engaged in a strenuous scroll test to confirm the document's scrollability on various devices, passing with flying colors.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-09-15 23:54 UTC, piotrpdev commented on CONTRIBUTING.md
> +- Add your dev namespace to the cluster’s `Namespace Bindings`.
I will update this section once/if #76 is merged

2023-09-18 11:18 UTC, devguyio requested changes
Thanks for doing this! I left a few comments

2023-09-18 11:18 UTC, devguyio commented on CONTRIBUTING.md
> +The main way to contribute is to work on tickets/issues that can be found on the [`opendatahub-io/ai-edge` project board](https://github.com/orgs/opendatahub-io/projects/47).
```suggestion
The following [`opendatahub-io/ai-edge`  GitHub Project board](https://github.com/orgs/opendatahub-io/projects/47) is the source of truth for the work taking place in this repo. You can pick up an issue from the TO DO column and follow the workflow described below. 
```

2023-09-18 11:18 UTC, devguyio commented on CONTRIBUTING.md
> +- If there is a roadblock to completing the issue, reach out to other people in the relevant OpenDataHub Slack channels ([invite](https://github.com/opendatahub-io/opendatahub-community)). We will gl
```suggestion
- If there is a roadblock to completing the issue, reach out on the relevant OpenDataHub Slack channels ([invite](https://github.com/opendatahub-io/opendatahub-community)). Someone will gladly try to help. 
```

2023-09-18 11:18 UTC, devguyio commented on CONTRIBUTING.md
> +    - We recommend you backup your local repo/changes before rebasing and/or squashing, to avoid crying and pain.
```suggestion
    - Rebasing and squashing can be tricky so be careful while performing it. You can also learn more about [squashing commits with rebase](https://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).
```

2023-09-18 11:18 UTC, devguyio commented on CONTRIBUTING.md
> +  - Create the Pull Request, apply the appropriate labels, and link the relevant GitHub issue to it. Also make sure to include a good description of your changes and screenshots if appropriate.
```suggestion
  - Create the pull request, apply the appropriate labels, and link the relevant GitHub issue to it. Also make sure to include a good description of your changes and screenshots if appropriate.
```

2023-09-18 11:18 UTC, devguyio commented on CONTRIBUTING.md
> +  - When you’re ready to make a Pull Request with your changes, first clean-up by rebasing and squashing the commits. Make sure to use clear and descriptive commit messages.
```suggestion
  - When you’re ready to make a pull request with your changes, first clean-up by rebasing and squashing the commits. Make sure to use clear and descriptive commit messages.
```

2023-09-18 11:18 UTC, devguyio commented on CONTRIBUTING.md
> +  - Once any conflicts and code suggestions have been resolved, and you work has been approved, you can merge the Pull Request or wait for somebody else to merge it for you.
```suggestion
  - Once any conflicts and code suggestions have been resolved, and your work has been approved, you can merge the pull request or wait for somebody else to merge it for you.
```

2023-09-18 11:53 UTC, piotrpdev commented
> Thanks for doing this! I left a few comments

Thanks for the review :smile:

2023-09-18 11:53 UTC, devguyio approved these changes

2023-09-18 13:11 UTC, piotrpdev commented
Will merge this if no more requested changes come in by the end of the day (~6PM `GMT+1` for me)

2023-09-18 16:07 UTC, merged